context:
  version: "0.1.35"

package:
  name: claude-agent-sdk
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/claude-agent-sdk/claude_agent_sdk-${{ version }}.tar.gz
  sha256: 0f98e2b3c71ca85abfc042e7a35c648df88e87fda41c52e6779ef7b038dcbb52

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir --no-deps -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - anyio >=4.0.0
    - mcp >=0.1.0
    - python >=${{ python_min }}
    - typing_extensions >=4.0.0
tests:
  - python:
      imports:
        - claude_agent_sdk
      pip_check: true

  - script: |
      python -m pytest tests/ -v || true
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - pytest-asyncio >=0.20.0
        - trio
    files:
      source:
        - CHANGELOG.md
        - tests/

about:
  homepage: https://github.com/anthropics/claude-agent-sdk-python
  summary: Python SDK for Claude Agent.
  description: Python SDK for Claude Agent.
  license: MIT
  license_file: LICENSE
  documentation: https://platform.claude.com/docs/en/agent-sdk/python
  repository: https://github.com/anthropics/claude-agent-sdk-python

extra:
  recipe-maintainers:
    - jan-janssen
    - MementoRC
