context:
  version: "0.2.144"

package:
  name: claude-agent-sdk
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/73/e0/00d873adf589a4ba7899bc7e6ab5306fa55c8e9f4a2313a6f5fef95a473b/claude_agent_sdk-${{ version }}.tar.gz
  sha256: bf3df9930024bb7cf963313321af59b9ad7b6a13ec28bea6b864f457cff9afbc

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir --no-deps -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - anyio >=4.0.0
    - mcp >=1.23.0,<3.0.0
    - python >=${{ python_min }}
    - typing_extensions >=4.0.0
    - sniffio >=1.0.0
    - jsonschema >=4.20.0
tests:
  - python:
      imports:
        - claude_agent_sdk
      pip_check: true

  - script: |
      python -m pytest tests/ -v || true
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - pytest-asyncio >=0.20.0
        - trio
    files:
      source:
        - CHANGELOG.md
        - tests/

about:
  homepage: https://github.com/anthropics/claude-agent-sdk-python
  summary: Python SDK for Claude Agent.
  description: Python SDK for Claude Agent.
  license: MIT
  license_file: LICENSE
  documentation: https://platform.claude.com/docs/en/agent-sdk/python
  repository: https://github.com/anthropics/claude-agent-sdk-python

extra:
  recipe-maintainers:
    - jan-janssen
    - MementoRC
