context:
  version: "0.2.149"

package:
  name: claude-agent-sdk
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/ed/d7/97d98a46fd6fc0723431e0d27a6f85033c96848eca55ba84cc03267a2607/claude_agent_sdk-${{ version }}.tar.gz
  sha256: 155a9240be13795f7d7cb491f1854b364821c6bc794184da59184a15d548bb14

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir --no-deps -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - anyio >=4.0.0
    - mcp >=1.23.0,<3.0.0
    - python >=${{ python_min }}
    - typing_extensions >=4.0.0
    - sniffio >=1.0.0
    - jsonschema >=4.20.0
tests:
  - python:
      imports:
        - claude_agent_sdk
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

  - script: |
      python -m pytest tests/ -v || true
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - pytest-asyncio >=0.20.0
        - trio
    files:
      source:
        - CHANGELOG.md
        - tests/

about:
  homepage: https://github.com/anthropics/claude-agent-sdk-python
  summary: Python SDK for Claude Agent.
  description: Python SDK for Claude Agent.
  license: MIT
  license_file: LICENSE
  documentation: https://platform.claude.com/docs/en/agent-sdk/python
  repository: https://github.com/anthropics/claude-agent-sdk-python

extra:
  recipe-maintainers:
    - jan-janssen
    - MementoRC
