context:
  version: "0.2.97"

package:
  name: claude-agent-sdk
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/fc/a2/50ba0002ef6ebfc3479244ce6fa309dfe914f57bf93df3faf72978d63249/claude_agent_sdk-${{ version }}.tar.gz
  sha256: 9104d15df11be5c95d36331968d49b17f30f0bb802415a19495744931bd76613

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir --no-deps -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - anyio >=4.0.0
    - mcp >=1.23.0,<2.0.0
    - python >=${{ python_min }}
    - typing_extensions >=4.0.0
    - sniffio >=1.0.0
tests:
  - python:
      imports:
        - claude_agent_sdk
      pip_check: true

  - script: |
      python -m pytest tests/ -v || true
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - pytest-asyncio >=0.20.0
        - trio
    files:
      source:
        - CHANGELOG.md
        - tests/

about:
  homepage: https://github.com/anthropics/claude-agent-sdk-python
  summary: Python SDK for Claude Agent.
  description: Python SDK for Claude Agent.
  license: MIT
  license_file: LICENSE
  documentation: https://platform.claude.com/docs/en/agent-sdk/python
  repository: https://github.com/anthropics/claude-agent-sdk-python

extra:
  recipe-maintainers:
    - jan-janssen
    - MementoRC
